---
name: End to End Tests

on:
  pull_request:

jobs:
  e2e:
    name: E2E
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        deploytool: ['operator', 'helm']
        globalnet: ['', 'globalnet']
        cable_driver: ['libreswan', 'strongswan', 'wireguard']
        ovn: ['', 'ovn']
        exclude:
          # Our Helm setup doesn’t know how to deploy other cable drivers
          - deploytool: 'helm'
            cable_driver: 'wireguard'
          - deploytool: 'helm'
            cable_driver: 'libreswan'
          - ovn: 'ovn'
            deploytool: 'helm'
          - ovn: 'ovn'
            globalnet: 'globalnet'
          - ovn: 'ovn'
            cable_driver: 'strongswan'
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Install WireGuard kernel module (only in WireGuard jobs)
        if: matrix.cable_driver == 'wireguard'
        run: |
          sudo apt install -y linux-headers-$(uname -r) wireguard
          sudo modprobe wireguard

      - name: Reclaim free space
        run: |
          # cleanup 30GB+ of tools we don't need for our CI ... bump
          rm -rf /opt/ghc /usr/share/dotnet /usr/share/swift
          df -h
          free -h

      - name: Run E2E deployment and tests
        run: |
          make e2e using="${{ matrix.globalnet }} ${{ matrix.deploytool }} ${{ matrix.cable_driver }} ${{ matrix.ovn }}"

      - name: Post mortem
        if: failure()
        run: |
          df -h
          free -h
          make post-mortem
